version: '3.8'

services:
  web-portal:
    build:
      context: .
      dockerfile: projects/web-portal/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./projects/web-portal:/app/projects/web-portal
      - /app/projects/web-portal/node_modules
    depends_on:
      - api-service

  user-portal:
    build:
      context: .
      dockerfile: projects/user-portal/Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./projects/user-portal:/app/projects/user-portal
      - /app/projects/user-portal/node_modules
    depends_on:
      - api-service

  admin-portal:
    build:
      context: .
      dockerfile: projects/admin-portal/Dockerfile
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./projects/admin-portal:/app/projects/admin-portal
      - /app/projects/admin-portal/node_modules
    depends_on:
      - api-service

  api-service:
    build:
      context: .
      dockerfile: projects/api-service/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - ./projects/api-service:/app/projects/api-service
      - /app/projects/api-service/node_modules

  # Local development services
  supabase-local:
    image: supabase/supabase-local
    ports:
      - "54321:8000"  # REST API
      - "54322:5432"  # PostgreSQL database
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./supabase/migrations:/migrations
      - supabase-data:/var/lib/postgresql/data

volumes:
  supabase-data: