name: CD

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project: [web-portal, user-portal, admin-portal, api-service]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build ${{ matrix.project }}
      run: |
        cd projects/${{ matrix.project }}
        npm run build || echo "No build script found, skipping..."
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./projects/${{ matrix.project }}/Dockerfile
        push: true
        tags: datainsight/${{ matrix.project }}:latest
        
    # Add deployment steps here based on your infrastructure
    # Examples:
    # - Deploy to Kubernetes
    # - Deploy to AWS ECS
    # - Deploy to Azure App Service